name: cardv1
description: Share Within A Snap.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  lottie: ^0.7.0
  flutter_svg: ^0.19.1
  flutter_rating_bar: ^3.0.1+1
  flutter_launcher_icons: ^0.8.1
  change_app_package_name: ^0.1.2
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher-playstore.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/ic_launcher-playstore.png
    - assets/lottie/splash_screen001.json
    - assets/lottie/splash_screen002.json
    - assets/lottie/splash_screen003.json
    - assets/lottie/splash_screen004.json
    - assets/lottie/splash_screen005.json
    - assets/lottie/splash_screen006.json
    - assets/lottie/splash_screen007.json
