/// Generated by AssetsRefGenerator on 2021/02/08
class Res {
  static const String ic_launcher-playstore = "assets/icons/ic_launcher-playstore.png";
  static const String splash_screen001 = "assets/lottie/splash_screen001.json";
  static const String splash_screen002 = "assets/lottie/splash_screen002.json";
  static const String splash_screen003 = "assets/lottie/splash_screen003.json";
  static const String splash_screen004 = "assets/lottie/splash_screen004.json";
  static const String splash_screen005 = "assets/lottie/splash_screen005.json";
  static const String splash_screen006 = "assets/lottie/splash_screen006.json";
  static const String splash_screen007 = "assets/lottie/splash_screen007.json";
}
